services:
  - type: web
    name: skillswap
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URI
        fromDatabase:
          name: skillswapdb
          property: connectionString

databases:
  - name: skillswapdb
    databaseName: skillswapdb
    user: daniel
